server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: microservice-registration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: stanko2014
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cryptonite
    username: cryptoadmin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000